OUTPUT_DIR = "./results"
MAX_INPUT_LENGTH = 128
MAX_TARGET_LENGTH = 128
MODEL_CHECKPOINT = "Helsinki-NLP/opus-mt-zh-en"

# OUTPUT_DIR = "./results"
# MAX_INPUT_LENGTH = 256
# MAX_TARGET_LENGTH = 256
# MODEL_CHECKPOINT = "facebook/m2m100_418M"